### ISSUE TITLE
 Resume multipart s3 uploading on error. Question.

### ISSUE THREAD

**Issue by danilke** [maximbilan/Swift-Amazon-S3-Uploading-Tutorial#2]
Hi, it's possible using aws-ios-sdk to implement a button, which resumes uploading to s3 when was an error? Thank you.

**Comment by maximbilan** [comment]
@danilke I guess you can do it with AWSS3TransferUtilityUploadTask. Please check it out here: https://aws.amazon.com/blogs/mobile/amazon-s3-transfer-utility-for-ios/
