### ISSUE TITLE
Getting No such module 'AWSS3'

### ISSUE THREAD

**Issue by anil-irestore** [maximbilan/Swift-Amazon-S3-Uploading-Tutorial#3]
I have installed through pods as you suggested in documentation file.
Its installed successfully, but, after imported the framework into class, its throwing as "No such module 'AWSS3'", even I removed derived data.

Can you help me, how to solve this?

**Comment by maximbilan** [comment]
@anil-irestore Are you sure that you were installing pods to the right target?

**Comment by rajaMishra1** [comment]
please use the pod file given below and install in your project pods--------------------->>>>>>>>>>>>>> 
pod 'AWSS3', '~> 2.6.13'   # For file transfers
